title: Conman's Dictionary
email: wwwwolf@iki.fi
description: >-
  A dictionary application for articial/constructed language enthusiasts.
domain: umbraroze.github.io
baseurl: /ConmanDictionary/
url: https://umbraroze.github.io
github_username: umbraroze
show_downloads: false

copyright: "Rose Midford"
author:
  name: "Rose Midford"
  location: "Oulu, Finland"
  email: "wwwwolf@iki.fi"
  fediverse: "@umbraroze@tech.lgbt"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/umbraroze
    - label: "Codeberg"
      icon: "fab fa-fw fa-forgejo"
      url: https://codeberg.org/umbraroze
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/umbraroze
    - label: "Codeberg"
      icon: "fab fa-fw fa-forgejo"
      url: https://codeberg.org/umbraroze

include:
 - .nojekyll

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "sunrise"

plugins:
 - jekyll-feed

