
title: Conman's Dictionary
email: wwwwolf@iki.fi
description: >-
  A dictionary application for articial/constructed language enthusiasts.
baseurl: ""
url: ""
github_username: umbraroze

#theme: midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
#  - jekyll-feed

